name: keepers

plugins:
  - name: alchemy
    version: "<0.7.0"

  - name: base
    version: "<0.7.0"

base:
  default_network: goerli
  goerli:
    default_provider: alchemy
    transaction_acceptance_timeout: 120
